import { db } from "./db";
import { financialGroups, transactionCategories } from "@shared/schema";
import { eq, and } from "drizzle-orm";

const FINANCIAL_GROUPS = [
  { name: "Ventas", type: "income", displayOrder: 1 },
  { name: "Inicio de Mes", type: "income", displayOrder: 2 },
  { name: "Otros Ingresos", type: "income", displayOrder: 3 },
  { name: "Banco, Tarjetas y Comisiones", type: "expense", displayOrder: 4 },
  { name: "Servicios", type: "expense", displayOrder: 5 },
  { name: "Alquiler", type: "expense", displayOrder: 6 },
  { name: "Compra de Bienes", type: "expense", displayOrder: 7 },
  { name: "Gastos Varios", type: "expense", displayOrder: 8 },
  { name: "Publicidad", type: "expense", displayOrder: 9 },
  { name: "Honorarios", type: "expense", displayOrder: 10 },
  { name: "Imprenta, Papelera y Articulos de Limpieza", type: "expense", displayOrder: 11 },
  { name: "Impuestos", type: "expense", displayOrder: 12 },
  { name: "Mantenimiento", type: "expense", displayOrder: 13 },
  { name: "Materiales e insumos", type: "expense", displayOrder: 14 },
  { name: "Materia Prima Barra", type: "expense", displayOrder: 15 },
  { name: "Materia Prima Cocina", type: "expense", displayOrder: 16 },
  { name: "Materia Prima Vinos", type: "expense", displayOrder: 17 },
  { name: "Musica", type: "expense", displayOrder: 18 },
  { name: "RRHH", type: "expense", displayOrder: 19 },
  { name: "Retiros Socios", type: "expense", displayOrder: 20 },
  { name: "Transferencias", type: "transfer", displayOrder: 21 },
];

const CATEGORIES_BY_GROUP: Record<string, { name: string; type: "income" | "expense" | "transfer" }[]> = {
  "Ventas": [
    { name: "Ventas Efectivo", type: "income" },
    { name: "Ventas Mercado Pago QR", type: "income" },
    { name: "Ventas Mercado Pago Tarjeta", type: "income" },
    { name: "Ventas Mercado Pago Transferencias", type: "income" },
    { name: "Ventas Mercado Pago Delivery", type: "income" },
    { name: "Ventas Tarjetas Crédito Banco", type: "income" },
    { name: "Ventas Tarjetas Débito Banco", type: "income" },
    { name: "Ventas Pedidos Ya", type: "income" },
    { name: "Ventas TIENDA FUDO", type: "income" },
    { name: "Ventas Rappi", type: "income" },
    { name: "Ventas MORFY", type: "income" },
    { name: "Ventas dólares", type: "income" },
    { name: "Ventas euros", type: "income" },
    { name: "Ventas Bitcoin", type: "income" },
    { name: "Ventas Efectivo (Mayorista)", type: "income" },
    { name: "Ventas Mercado Pago QR (Mayorista)", type: "income" },
    { name: "Ventas Mercado Pago Tarjeta (Mayorista)", type: "income" },
    { name: "Ventas Mercado Pago Transferencias (Mayorista)", type: "income" },
    { name: "Ventas Mercado Pago Delivery (Mayorista)", type: "income" },
    { name: "Ventas Tarjetas Crédito Bco (Mayorista)", type: "income" },
    { name: "Ventas Tarjetas Débito Bco (Mayorista)", type: "income" },
    { name: "Ventas Pedidos Ya (Mayorista)", type: "income" },
    { name: "Ventas Rappi (Mayorista)", type: "income" },
    { name: "Ventas dólares (Mayorista)", type: "income" },
    { name: "Ventas euros (Mayorista)", type: "income" },
    { name: "Ventas Bitcoin (Mayorista)", type: "income" },
  ],
  "Inicio de Mes": [
    { name: "Inicio de mes", type: "income" },
  ],
  "Otros Ingresos": [
    { name: "Préstamos", type: "income" },
    { name: "Ajustes y diferencia de caja (sobrante efec.)", type: "income" },
    { name: "Rendimientos por Billeteras Virtuales", type: "income" },
    { name: "Rendimiento Mercado Pago", type: "income" },
    { name: "Rendimientos FIMA", type: "income" },
    { name: "Otros Rendimientos", type: "income" },
    { name: "Ingreso de Capital Préstamo", type: "income" },
    { name: "Ingreso de Capital Socios", type: "income" },
    { name: "Ajustes y diferencia de caja (sobrante efec.) (Mayorista)", type: "income" },
    { name: "Rendimientos Mercado Pago (Mayorista)", type: "income" },
    { name: "Rendimientos FIMA (Mayorista)", type: "income" },
    { name: "Otros Rendimientos (Mayorista)", type: "income" },
    { name: "Ingreso de Capital Préstamo (Mayorista)", type: "income" },
    { name: "Ingreso de Capital Socios (Mayorista)", type: "income" },
  ],
  "Banco, Tarjetas y Comisiones": [
    { name: "Comisiones Mercado Pago", type: "expense" },
    { name: "Comisiones Tarjetas de crédito", type: "expense" },
    { name: "Comisiones Tarjetas de débito", type: "expense" },
    { name: "Mantenimiento y comisiones", type: "expense" },
    { name: "Comisión por ventas Pedidos Ya", type: "expense" },
    { name: "Comisión por ventas Rappi", type: "expense" },
    { name: "Comisión por transferencias Mercado Pago", type: "expense" },
    { name: "Comisión por transferencias Banco", type: "expense" },
    { name: "Comisión por venta Morfy", type: "expense" },
    { name: "Comisión por venta Delivery propio", type: "expense" },
  ],
  "Servicios": [
    { name: "Hosting, abono mails, etc.", type: "expense" },
    { name: "Agua", type: "expense" },
    { name: "Alarma", type: "expense" },
    { name: "Bizneo", type: "expense" },
    { name: "Cable e internet", type: "expense" },
    { name: "Electricidad", type: "expense" },
    { name: "Gas", type: "expense" },
    { name: "Global identi", type: "expense" },
    { name: "Otros Seguros", type: "expense" },
    { name: "Seguro", type: "expense" },
    { name: "Seguro ART eventual", type: "expense" },
    { name: "Servicio de emergencias", type: "expense" },
    { name: "Sistema o Software de gestión (adm. y comanda)", type: "expense" },
    { name: "Sistema o Software para reservas", type: "expense" },
    { name: "Spotify", type: "expense" },
    { name: "Telefonía", type: "expense" },
  ],
  "Alquiler": [
    { name: "Expensas", type: "expense" },
    { name: "Alquiler", type: "expense" },
    { name: "Alquiler oficina central", type: "expense" },
    { name: "Remito", type: "expense" },
    { name: "Retenciones alquiler", type: "expense" },
  ],
  "Compra de Bienes": [
    { name: "Computadoras y electrónica", type: "expense" },
    { name: "Equipos de audio", type: "expense" },
    { name: "Equipos gastronómicos", type: "expense" },
    { name: "Equipamiento para Servicio", type: "expense" },
    { name: "Inversión estructural", type: "expense" },
    { name: "Mejora Bienes de Uso", type: "expense" },
    { name: "Mobiliario Cocina", type: "expense" },
    { name: "Mobiliario Salón", type: "expense" },
    { name: "Mobiliario Barra", type: "expense" },
    { name: "Uniformes", type: "expense" },
  ],
  "Gastos Varios": [
    { name: "interés sobre cuota de préstamo", type: "expense" },
    { name: "Artículos varios", type: "expense" },
    { name: "Ajustes y diferencia de caja (faltante efec.)", type: "expense" },
    { name: "Alquiler calefacción o refrigeración", type: "expense" },
    { name: "Alquiler Técnica o Luces", type: "expense" },
    { name: "Alquiler Vajilla", type: "expense" },
    { name: "Billete falso o dañado", type: "expense" },
    { name: "Certificaciones, Balances, Multas", type: "expense" },
    { name: "Cigarrillos", type: "expense" },
    { name: "Combustible", type: "expense" },
    { name: "Comida de personal, comida producciones", type: "expense" },
    { name: "Comisiones EVENTOS", type: "expense" },
    { name: "Correo, cartas documento", type: "expense" },
    { name: "Farmacia, botiquín, medicamentos", type: "expense" },
    { name: "Fletes", type: "expense" },
    { name: "Gastos de Representación", type: "expense" },
    { name: "Higiene, barbijos, alcohol en gel, etc", type: "expense" },
    { name: "Librería y gastos de oficina", type: "expense" },
    { name: "Mesa impaga o Cortesías", type: "expense" },
    { name: "Movilidad: Envío de productos o materia prima", type: "expense" },
    { name: "Movilidad: Traslado de personal", type: "expense" },
    { name: "Retiro de basura", type: "expense" },
    { name: "Rodados", type: "expense" },
    { name: "Sellados y boletas GCBA", type: "expense" },
    { name: "Varios", type: "expense" },
    { name: "Velas", type: "expense" },
    { name: "Vivero, flores, macetas", type: "expense" },
    { name: "Váucher o canjes", type: "expense" },
    { name: "lavandería", type: "expense" },
    { name: "Fees Franquicias", type: "expense" },
    { name: "cortesía de la casa", type: "expense" },
    { name: "Lavadero", type: "expense" },
  ],
  "Publicidad": [
    { name: "Publicidad folletería", type: "expense" },
    { name: "cortesía Publicidad", type: "expense" },
    { name: "Publicidad en Internet", type: "expense" },
    { name: "Publicidad vía Publica", type: "expense" },
  ],
  "Honorarios": [
    { name: "Abogado", type: "expense" },
    { name: "Arquitecto", type: "expense" },
    { name: "Asesoramiento", type: "expense" },
    { name: "Audiovisual y producciones", type: "expense" },
    { name: "Community Manager", type: "expense" },
    { name: "Contador", type: "expense" },
    { name: "Diseño gráfico", type: "expense" },
    { name: "Escribano", type: "expense" },
    { name: "Gastos de Importación", type: "expense" },
    { name: "Limpieza", type: "expense" },
    { name: "Gestor", type: "expense" },
    { name: "Paisajista", type: "expense" },
    { name: "Productora DJs", type: "expense" },
    { name: "Trabajo Socios", type: "expense" },
    { name: "Estudio medicinal empleados", type: "expense" },
  ],
  "Imprenta, Papelera y Articulos de Limpieza": [
    { name: "Reimpresiones de carta", type: "expense" },
    { name: "Packagings, descartables, cajas", type: "expense" },
    { name: "Vinilos, etiquetas, etc", type: "expense" },
    { name: "Material Descartable", type: "expense" },
    { name: "Productos de Limpieza", type: "expense" },
  ],
  "Impuestos": [
    { name: "ABL", type: "expense" },
    { name: "Adicapif", type: "expense" },
    { name: "Autónomos", type: "expense" },
    { name: "Ganancias", type: "expense" },
    { name: "Ganancias anticipos", type: "expense" },
    { name: "Ganancias Retenciones", type: "expense" },
    { name: "IIBB Retenciones", type: "expense" },
    { name: "Ingresos Brutos CABA", type: "expense" },
    { name: "IVA Afip", type: "expense" },
    { name: "IVA Facturas", type: "expense" },
    { name: "IVA Retenciones", type: "expense" },
    { name: "IVA Percepciones", type: "expense" },
    { name: "Impuestos Varios", type: "expense" },
    { name: "Ley de cheques, débito, crédito", type: "expense" },
    { name: "Monotributo", type: "expense" },
    { name: "Plan de pago/Moratoria", type: "expense" },
    { name: "Sadaic", type: "expense" },
    { name: "Seguridad Social Retenciones", type: "expense" },
    { name: "Impuesto sobre el Debito", type: "expense" },
    { name: "Impuesto sobre el Crédito", type: "expense" },
    { name: "Impuesto Afip 4815", type: "expense" },
  ],
  "Mantenimiento": [
    { name: "Aire Acondicionado", type: "expense" },
    { name: "Arreglo Equipos", type: "expense" },
    { name: "Arreglo instalaciones", type: "expense" },
    { name: "Arreglo Mobiliario", type: "expense" },
    { name: "Cámaras de seguridad", type: "expense" },
    { name: "Cerrajería, copia de llaves, candados", type: "expense" },
    { name: "Compras Ferretería", type: "expense" },
    { name: "Compras Pinturería", type: "expense" },
    { name: "Fumigación", type: "expense" },
    { name: "Jornales Mantenimiento", type: "expense" },
    { name: "Limpieza de Campana", type: "expense" },
    { name: "Limpieza de Tanque", type: "expense" },
    { name: "Limpieza de Vidrios", type: "expense" },
    { name: "Limpieza de Canillas", type: "expense" },
    { name: "Matafuegos", type: "expense" },
    { name: "Material de Limpieza", type: "expense" },
    { name: "Montacargas", type: "expense" },
    { name: "Plan de evacuación", type: "expense" },
    { name: "Preservativos", type: "expense" },
    { name: "Pro Higiene", type: "expense" },
    { name: "Tratamiento ignífugo", type: "expense" },
    { name: "Otros Gs. Mantenimiento", type: "expense" },
    { name: "Materiales", type: "expense" },
    { name: "Recarga tubo gas", type: "expense" },
  ],
  "Materiales e insumos": [
    { name: "Menta y especias", type: "expense" },
    { name: "Miel", type: "expense" },
    { name: "Café", type: "expense" },
    { name: "Materia Prima", type: "expense" },
    { name: "Mercadería de Reventa", type: "expense" },
    { name: "Almacén Varios", type: "expense" },
    { name: "Embutidos", type: "expense" },
    { name: "Helados", type: "expense" },
    { name: "Laminados", type: "expense" },
    { name: "Postres", type: "expense" },
  ],
  "Materia Prima Barra": [
    { name: "Aguas y Sodas", type: "expense" },
    { name: "Almacén de Barra", type: "expense" },
    { name: "Bebidas", type: "expense" },
    { name: "Café / Té", type: "expense" },
    { name: "Cervezas", type: "expense" },
    { name: "Flores comestibles", type: "expense" },
    { name: "Frutos Rojos, Pulpas y Jugos", type: "expense" },
    { name: "Gaseosas", type: "expense" },
    { name: "Hielo", type: "expense" },
    { name: "Kombuchas", type: "expense" },
  ],
  "Materia Prima Cocina": [
    { name: "Verdulería cítricos", type: "expense" },
    { name: "Aceite", type: "expense" },
    { name: "Carnes y frigoríficos", type: "expense" },
    { name: "Congelados", type: "expense" },
    { name: "Especias y Frutos Secos", type: "expense" },
    { name: "Granja (Huevos, etc)", type: "expense" },
    { name: "Harina", type: "expense" },
    { name: "Hongos", type: "expense" },
    { name: "Lácteos (Quesos, leche, etc)", type: "expense" },
    { name: "Pan", type: "expense" },
    { name: "Pescados y Mariscos", type: "expense" },
    { name: "Pizza", type: "expense" },
    { name: "Verdulería", type: "expense" },
  ],
  "Materia Prima Vinos": [
    { name: "Vinos", type: "expense" },
  ],
  "Musica": [
    { name: "Banda", type: "expense" },
    { name: "Cantante", type: "expense" },
    { name: "DJ", type: "expense" },
  ],
  "RRHH": [
    { name: "Gerencia", type: "expense" },
    { name: "Cargas sociales", type: "expense" },
    { name: "Sindicato", type: "expense" },
    { name: "Aguinaldos", type: "expense" },
    { name: "Anticipo de sueldos", type: "expense" },
    { name: "Bachero", type: "expense" },
    { name: "Barista", type: "expense" },
    { name: "Bartender", type: "expense" },
    { name: "Cajero", type: "expense" },
    { name: "Cocina", type: "expense" },
    { name: "Comisiones Empleados", type: "expense" },
    { name: "Días de prueba y eventuales", type: "expense" },
    { name: "Encargado", type: "expense" },
    { name: "Recursos Humanos", type: "expense" },
    { name: "Equipo de Administración", type: "expense" },
    { name: "Equipo de Compras", type: "expense" },
    { name: "Equipo de Producción", type: "expense" },
    { name: "Extras Personal", type: "expense" },
    { name: "Liquidación Final", type: "expense" },
    { name: "Mozo / Salón", type: "expense" },
    { name: "Propinas de EVENTOS", type: "expense" },
    { name: "Recepción", type: "expense" },
    { name: "Sueldos", type: "expense" },
    { name: "Vacaciones", type: "expense" },
    { name: "Viandas/Comida del personal", type: "expense" },
  ],
  "Retiros Socios": [
    { name: "Retiro de dinero Socios", type: "expense" },
    { name: "Retiro de dinero (Mayorista)", type: "expense" },
    { name: "Pagos AMEX empresarial", type: "expense" },
    { name: "Pagos AMEX empresarial (Mayorista)", type: "expense" },
  ],
  "Transferencias": [
    { name: "Ingreso por transferencia entre cuentas", type: "transfer" },
    { name: "Egreso por transferencia entre cuentas", type: "transfer" },
    { name: "Ingreso por transferencia entre cuentas (Mayorista)", type: "transfer" },
    { name: "Egreso por transferencia entre cuentas (Mayorista)", type: "transfer" },
  ],
};

export async function seedFinancialDataForClient(clientId: number): Promise<{ groups: number; categories: number }> {
  let groupsCreated = 0;
  let categoriesCreated = 0;

  const existingGroups = await db.select().from(financialGroups).where(eq(financialGroups.clientId, clientId));
  
  if (existingGroups.length > 0) {
    console.log(`Client ${clientId} already has ${existingGroups.length} financial groups. Skipping seed.`);
    return { groups: 0, categories: 0 };
  }

  const groupIdMap: Record<string, number> = {};

  for (const group of FINANCIAL_GROUPS) {
    const [inserted] = await db.insert(financialGroups).values({
      clientId,
      name: group.name,
      type: group.type as "income" | "expense" | "transfer",
      displayOrder: group.displayOrder,
      isSystem: true,
    }).returning();
    
    groupIdMap[group.name] = inserted.id;
    groupsCreated++;
  }

  for (const [groupName, categories] of Object.entries(CATEGORIES_BY_GROUP)) {
    const groupId = groupIdMap[groupName];
    if (!groupId) {
      console.warn(`Group "${groupName}" not found in map, skipping categories`);
      continue;
    }

    for (const cat of categories) {
      await db.insert(transactionCategories).values({
        clientId,
        name: cat.name,
        type: cat.type,
        financialGroupId: groupId,
        isSystem: true,
        active: true,
      });
      categoriesCreated++;
    }
  }

  console.log(`Seeded ${groupsCreated} groups and ${categoriesCreated} categories for client ${clientId}`);
  return { groups: groupsCreated, categories: categoriesCreated };
}
